<a href="https://colab.research.google.com/github/GunjanJ2027/Image_Processing-Computer_Vision-2301010062-/blob/main/Experiment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np

In [ ]:
img = cv2.imread('/content/sample_data/ipcv image.jpeg', 0)

if img is None:
    print('Error: Could not load image. Please check the file path.')
else:
    print('Image loaded successfully.')

Image loaded successfully.


In [ ]:
gauss = img + np.random.normal(0, 20, img.shape)
gauss = np.clip(gauss, 0, 255).astype(np.uint8)

In [ ]:
print(gauss)

[[ 32  38  36 ...  14   0   0]
 [  6  28  24 ...  15   0  26]
 [ 43  45  36 ...  58   0  13]
 ...
 [236 255 222 ...  19   8   0]
 [255 255 255 ...   2   0   0]
 [254 230 255 ...   0  23   0]]


In [ ]:
sp = img.copy()

In [ ]:
prob = 0.02
rand = np.random.rand(*img.shape)
sp[rand<prob]=0

In [ ]:
sp[rand>1-prob]= 255


In [ ]:
print(rand)

[[0.68643748 0.26435127 0.13779071 ... 0.09331246 0.7624157  0.05219383]
 [0.4834016  0.23052762 0.5488392  ... 0.80546817 0.80675655 0.43141194]
 [0.64422464 0.25220359 0.76526829 ... 0.78939841 0.63642518 0.2117817 ]
 ...
 [0.83814132 0.83687099 0.55959105 ... 0.26936243 0.72384164 0.9982386 ]
 [0.13107979 0.30291209 0.88898205 ... 0.69587508 0.71556793 0.09001313]
 [0.61886393 0.5509074  0.60735482 ... 0.34241567 0.70219985 0.98025486]]


In [ ]:
cv2.imwrite("gauss.jpg", gauss)

True

In [ ]:
from google.colab import files
files.download("gauss.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
cv2.imwrite("sp.jpg", sp)

True

In [ ]:
files.download("sp.jpg")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
mean_filt= cv2.blur(gauss,(3,3))

In [ ]:
median_filt= cv2.medianBlur(sp,3)

In [ ]:
cv2.imwrite("gauss2.jpg", mean_filt)

True

In [ ]:
files.download("gauss2.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
cv2.imwrite("gauss3.jpg", median_filt)

True

In [ ]:
files.download("gauss3.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>